version: '3.9'

services:
  database:
    image: postgres:14
    container_name: petani-database
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    restart: always

volumes:
  postgres:
